rootDir: ".config"
outDir: "."

mergeRules:
  ".husky/commit-msg": true
  ".vscode/cspell.json": [ "words" ]
  ".vscode/launch.json": [ "configurations" ]
  ".gitignore": true
  ".npmignore": true
  "jest.modules.json": [ "es6" ]
  "typedoc.json": [ "entryPoints" ]

ignorePatterns:
  ".gitignore": [
    "*.log",
    "*.pid",
    "*.pid.lock",
    "*.seed",
    "*.tgz",
    ".editorconfig",
    ".env",
    ".eslintcache",
    ".eslintignore",
    ".eslintrc",
    ".prettierignore",
    ".prettierrc",
    ".yarn-integrity",
    "/.husky/",
    "/.vscode/",
    "/jest.modules.json",
    "/typedoc.json",
    "babel.config.js",
    "codecov.yml",
    "coverage",
    "jest.config.js",
    "lib",
    "logs",
    "node_modules/",
    "pids",
    "tsconfig.json",
    "tsconfig.tsbuildinfo",
    "yarn-debug.log*",
    "yarn-error.log*"
  ]
  ".npmignore": [
    "**/__mocks__/**",
    "**/__tests__/**",
    ".changelogrc.yml",
    ".config",
    ".editorconfig",
    ".env",
    ".eslintignore",
    ".eslintrc",
    ".ghinfo",
    ".gitattributes",
    ".github",
    ".husky",
    ".prettierignore",
    ".prettierrc",
    ".vscode",
    "CODE_OF_CONDUCT.md",
    "babel.config.js",
    "codecov.yml",
    "codegen.yml",
    "coverage/",
    "docs/",
    "example/",
    "jest.config.js",
    "jest.modules.json",
    "media/",
    "node_modules/",
    "src/",
    "tsconfig.json",
    "typedoc.json"
  ]
  ".eslintignore": [
    "*.gql",
    "*.js",
    "__generated__",
    "lib"
  ]
  ".prettierignore": [
    "lib/"
  ]

executableFiles: [
  ".husky/commit-msg",
  ".husky/pre-commit",
]

scripts:
  "prepare:config": "ts-package-shared-config"
  "prepare:husky": "husky install"
  "prepare": "npm-run-all prepare:*"
  "check:lint": "rimraf coverage && eslint \"src/**\" --ext .ts"
  "check:spell": "cspell -c .vscode/cspell.json --no-summary \"README.md\" \"src/**/*.ts\""
  "check": "npm-run-all check:*"
  "test:jest": "jest"
  "test": "npm-run-all test:*"
  "generate:changelog": "changelog generate --bump"
  "generate:docs": "rimraf docs/api && typedoc"
  "generate:ghinfo": "ghinfo generate -d media -t utils"
  "generate": "npm-run-all generate:*"
  "build:ts": "rimraf lib && tsc --extendedDiagnostics"
  "build": "npm-run-all build:*"
  "release": "npm-run-all prepare check test build generate"

dependencies:
  - "@babel/plugin-transform-runtime": "7.x"
  - "@babel/preset-env": "7.x"
  - "@types/jest": "26.x"
  - "@types/node": "14.x"
  - "@typescript-eslint/eslint-plugin": "4.x"
  - "@typescript-eslint/parser": "4.x"
  - "babel-jest": "26.x"
  - "changelog-guru"
  - "cspell"
  - "eslint": "7.x"
  - "eslint-config-prettier": "8.x"
  - "eslint-plugin-import": "2.x"
  - "eslint-plugin-jest": 24.x"
  - "eslint-plugin-node": "11.x"
  - "eslint-plugin-optimize-regex": "1.x"
  - "eslint-plugin-promise": "5.x"
  - "ghinfo"
  - "husky": "6.x"
  - "jest": "26.x"
  - "npm-run-all"
  - "prettier"
  - "rimraf"
  - "ts-jest": "26.x"
  - "typedoc": "0.20.x"
  - "typedoc-plugin-markdown": "3.x"
  - "typescript": "4.x"
