sharedDir: '.config'
outputDir: 'lib'

mergeRules:
  '.husky/commit-msg': true
  '.vscode/launch.json': ['configurations']
  'tsconfig.json': ['include']
  '.gitignore': true
  '.npmignore': true

ignorePatterns:
  '.gitignore':
    [
      '*.log',
      '*.pid',
      '*.pid.lock',
      '*.seed',
      '*.tgz',
      '.env',
      '.eslintrc',
      '.yarn-integrity',
      '/.eslintcache',
      '/.eslintignore',
      '/.husky/',
      '/jest.config.js',
      'coverage',
      'lib',
      'logs',
      'node_modules/',
      'pids',
      '/tsconfig.json',
      '/src/**/tsconfig.json',
      'tsconfig.tsbuildinfo',
      'yarn-debug.log*',
      'yarn-error.log*',
    ]
  '.npmignore':
    [
      '**/__benchmark__/**',
      '**/__mocks__/**',
      '**/__tests__/**',
      '.changelogrc.yml',
      '.config',
      '.env',
      '.eslintignore',
      '.eslintrc',
      '.ghinfo',
      '.gitattributes',
      '.github',
      '.husky',
      'CODE_OF_CONDUCT.md',
      'codecov.yml',
      'codegen.yml',
      'coverage/',
      'docs/',
      'example/',
      'jest.config.js',
      'media/',
      'node_modules/',
      'src/',
      'tsconfig.json',
      'typings/',
    ]
  '.eslintignore': ['*.gql', '*.js', '__generated__', 'lib']
  '.prettierignore': ['lib/']

executableFiles: ['.husky/commit-msg', '.husky/pre-commit']

scripts:
  'build': 'run-s build:*'
  'build:ts': 'rimraf lib && tsc --extendedDiagnostics'
  'generate': 'run-s generate:*'
  'generate:changelog': 'changelog generate --bump'
  'generate:ghinfo': 'ghinfo generate -d media -t utils'
  'lint': 'run-s lint:*'
  'lint:eslint': 'rimraf coverage && eslint src --ext .ts'
  'prepare': 'run-s prepare:*'
  'prepare:config': 'ts-package-shared-config'
  'prepare:husky': 'husky install'
  'release': 'run-s prepare lint test build generate'
  'test': 'run-s test:*'
  'test:jest': 'node --experimental-vm-modules node_modules/.bin/jest'

package:
  exports: './lib/index.js'
  manager: 'npm'
  type: 'module'
  types: './lib/index.d.ts'
