rootDir: ".config"
outDir: "."

rules:
  ".husky/commit-msg": true
  ".vscode/cspell.json": [ "words" ]
  ".vscode/launch.json": [ "configurations" ]
  ".gitignore": true
  ".npmignore": true
  "jest.modules.json": [ "es6" ]
  "typedoc.json": [ "entryPoints" ]

scripts:
  "prepare:config": "ts-package-shared-config"
  "prepare:husky": "husky install"
  "prepare": "npm-run-all prepare:*"
  "check:lint": "rimraf coverage && eslint \"src/**\" --ext .ts"
  "check:spell": "cspell -c .vscode/cspell.json --no-summary \"README.md\" \"src/**/*.ts\""
  "check": "npm-run-all check:*"
  "test:jest": "jest"
  "test": "npm-run-all test:*"
  "generate:changelog": "changelog generate --bump"
  "generate:docs": "rimraf docs/api && typedoc"
  "generate:ghinfo": "ghinfo generate -d media -t utils"
  "generate": "npm-run-all generate:*"
  "build:ts": "rimraf lib && tsc --extendedDiagnostics"
  "build": "npm-run-all build:*"
  "release": "npm-run-all prepare check test build generate"

dependencies:
  - "@types/jest"
  - "@types/node"
  - "@typescript-eslint/eslint-plugin"
  - "@typescript-eslint/parser"
  - "changelog-guru"
  - "cspell"
  - "eslint"
  - "eslint-config-prettier"
  - "eslint-plugin-import"
  - "eslint-plugin-jest"
  - "eslint-plugin-node"
  - "eslint-plugin-optimize-regex"
  - "eslint-plugin-promise"
  - "ghinfo"
  - "husky": "6.x"
  - "jest"
  - "npm-run-all"
  - "prettier"
  - "rimraf"
  - "ts-jest"
  - "typedoc": "0.20.x"
  - "typedoc-plugin-markdown": "3.x"
  - "typescript": "4.x"
